FROM ubuntu:22.04

WORKDIR /root

COPY ./requirements.txt ./
RUN apt-get update && \
    apt-get install -y tmux vim htop \  
                    python3.10 python3-pip && \
    pip3 install torch torchvision torchaudio --index-url \ 
                    https://download.pytorch.org/whl/cu121 && \
    pip3 install --no-cache-dir -r requirements.txt 

COPY ./src ./
